version: '3.8'

services:
  postgres:
    image: postgres
    container_name: my_postgres
    restart: always
    env_file:
    - docker.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user-crud-operation

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4:4.26
    ports:
      - "8080:80"
    volumes:
      - ./data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - user-crud-operation

volumes:
  postgres_data:
networks:
  user-crud-operation:
    driver: bridge
